language: node_js
node_js:
  - 11
  - 10
  - 8

jobs:
  include:
    - stage: release
      node_js: lts/*
      before_deploy:
        - yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - set -e ; yarn semantic-release
